- name: Deploy multitier app cloud instances in OpenStack
  hosts: localhost
  tasks:
    - name: Fetch Instance Info
      os_server_info:
        cloud: openstack
        region_name: regionOne
      register: r_os_servers

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group:
          - "{{ item.metadata.group }}"
          - "{{ item.metadata.deployment_name }}"
        ansible_user: cloud-user
      loop: "{{ r_os_servers.openstack_servers }}"

- import_playbook: provision_database_tier.yml
- import_playbook: provision_app_tier.yml
- import_playbook: provision_load_balancer_tier.yml
- import_playbook: smoke_test.yml

